repos:
  - repo: local
    hooks:

      - id: python-linting
        name: python-linting
        entry: poetry run task lint
        language: system
        types_or: [python]
          
      - id: python-testing
        name: python-testing
        entry: poetry run task test
        language: system
        types_or: [python]
