version: "3"

tasks:
  install:
    desc: Installs the dependencies.
    cmds:
      - poetry install --no-root
      - poetry run pre-commit install

  lint:
    desc: Lints the code and report issues.
    cmds:
      - poetry run mypy github_cli
      - poetry run black github_cli
      - poetry run flake8 github_cli --show-source --statistics --count
      - poetry run pylint github_cli

  test:
    desc: Runs test on code
    cmds: 
      - poetry run pytest

  build:
      desc: Builds the python package
      cmds:
        - poetry build
