version: "3"

tasks:
  install:
    desc: Installs the dependencies.
    cmds:
      - poetry install --no-root

  lint:
    desc: Lints the code and report issues.
    cmds:
      - poetry run mypy gh_star_count
      - poetry run black gh_star_count
      - poetry run flake8 gh_star_count --show-source --statistics --count
      - poetry run pylint gh_star_count

  test:
    desc: Runs test on code
    cmds: 
      - poetry run pytest

  build:
      desc: Builds the python package
      cmds:
        - poetry build
