version: "3"

tasks:
  install:
    desc: Installs the dependencies.
    cmds:
      - poetry install --no-root

  lint:
    desc: Lints the code and report issues.
    cmds:
      - poetry run mypy github_cli
      - poetry run black --check github_cli
      - poetry run flake8 github_cli --show-source --statistics --count
      - poetry run pylint github_cli

  build:
      desc: Builds the puthon package
      cmds:
        - poetry build
