version: "3"

tasks:
  install:
    desc: Installs the dependencies.
    cmds:
      - poetry install --no-root

  lint:
    desc: Lints the code and report issues.
    cmds:
      - poetry run mypy gh_star_count
      - poetry run black gh_star_count
      - poetry run flake8 gh_star_count --show-source --statistics --count
      - poetry run pylint gh_star_count

  test:
    desc: Runs test on code
    cmds: 
      - >
        poetry run pytest
        --cov=gh_star_count
        --cov-report=html

  build:
      desc: Builds the python package
      cmds:
        - poetry build

  docs-serve:
    desc: Serve the documentation locally
    deps:
      - test
      - generate-changelog
    cmds:
      - poetry run mkdocs serve

  docs-publish:
    desc: Publish the documentation to gh-pages
    deps:
      - generate-changelog
    cmds:
      - poetry run gh-deploy --force

  generate-changelog:
    desc: Generates the changelog
    cmds:
      - poetry run git-changelog --output CHANGELOG.md
